version: '3.6'
services:

  mysql-master:
    image: mysql:8.4
    env_file: configuration.env
    ports:
      - 3306:3306
    volumes:
      - master_data:/var/lib/mysql
      - ./mysql/master/conf.d:/etc/mysql/conf.d
      - ./scripts/insert_employees.sh:/usr/local/bin/insert_employees.sh # Copy script to run db load
      - ./scripts/setup_replica_user.sql:/docker-entrypoint-initdb.d/1.sql # Create user for data replication
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/2.sql # Create table
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 20
    networks:
      - backend

  mysql-slave1:
    image: mysql:8.4
    env_file: configuration.env
    ports:
      - 3307:3306
    volumes:
      - slave1_data:/var/lib/mysql
      - ./mysql/slave1/conf.d:/etc/mysql/conf.d
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/1.sql # Create table
    depends_on:
      mysql-master:
        condition: service_healthy
    networks:
      - backend

  mysql-slave2:
    image: mysql:8.4
    env_file: configuration.env
    ports:
      - 3308:3306
    volumes:
      - slave2_data:/var/lib/mysql
      - ./mysql/slave2/conf.d:/etc/mysql/conf.d
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/1.sql # Create table
    depends_on:
      mysql-master:
        condition: service_healthy
    networks:
      - backend

volumes:
  master_data:
  slave1_data:
  slave2_data:

networks:
  backend:
    driver: bridge
